config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root to: 'articles#index'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	require 'read-time'

	

	# def reading_time
 #     (word_count / 10.0).ceil
	# end

	# def word_count
	# 	blog.split.size
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  before_action only: %i[show edit update destroy]

  # before_action only: %i[new create] do
  #   @article = Article.new
  # end


  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params.require(:article).permit(:auth_name, :blog))
    # @article.auth_name= params[:article][:auth_name]
    # @article.blog= params[:article][:blog]
        
    if @article.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(params.require(:article).permit(:auth_name, :blog))
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
   Article.find(params[:id]).destroy
    redirect_to action: 'index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/delete.html.erb
<h1>Articles#delete</h1>
<p>Find me in app/views/articles/delete.html.erb</p>

app/views/articles/edit.html.erb
<h1> <%= @article.auth_name %></h1>
<h1> <%= @article.blog %></h1>

<h2>To Edit that</h2>
<%= form_for @article, action: "update", method: 'put' do |a|%>
<%= a.text_field :auth_name%><br>
<%= a.text_field :blog%>
<%= a.submit%>
<%end%>

app/views/articles/index.html.erb
<% if @articles.blank? %>
<p>There are no article currently in the system.</p>
<% else %>
<p>These are the current authors in our system</p>

<ul id = "article">
   <% @articles.each do |a| %>
   <li><%=link_to a.auth_name, article_path(a.id) %>           <%= a.blog.readtime %> </li>
   <% end %>
</ul>

<% end %>
<p><%= link_to "Add new article", new_article_path %></p>

app/views/articles/new.html.erb
<h1>Add new article</h1>

<h1>Fill-up</h1>


<%= form_for @article do |a|%>
<%= a.text_field :auth_name%><br>
<%= a.text_area :blog%>
<%= a.submit%>
<%end%>

app/views/articles/show.html.erb
<h1>Name: <%= @article.auth_name %></h1>
<h2>Content:</h2>
<p id="article-content"><%= @article.blog%></p>
<p>Read Time: <%= @article.blog.readtime %></p>
<p id="js-read-time">Read Time from JS: <span></span></p>

<%= link_to("edit", action: "edit", controller: "articles", id: @article.id)%>
<br>
<%#= link_to("Delete", "#{@country.id}", method: :delete)%>
<%= link_to("Delete", article_path(@article.id), method: :delete)%>
<hr />

<%= link_to 'Back', action: 'index', controller: "articles" %>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReadTime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>